version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:14

jobs:
  build:
    executor: node-executor
    environment:
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      AWS_DEFAULT_REGION: ap-south-1
    steps:
      - checkout
      - run:
          name: Install AWS CDK
          command: sudo npm install -g aws-cdk
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build
          command: npm run build
      - run:
          name: Deploy Stack
          command: |
            cdk deploy AlbStack

  manual_approval:
    type: approval

workflows:
  version: 2
  deploy:
    jobs:
      - build
      - manual_approval:
          requires:
            - build
